tmux:
  symbols:
    branch: ' '
    hashprefix: ' '
    ahead: ↑·
    behind: ↓·
    staged: '● '
    conflict: '✖ '
    modified: '✚'
    untracked: '…'
    stashed: '⚑ '
    clean: 
  styles:
    state: '#[fg=red,bold]'
    branch: '#[fg=colour172]'
    remote: '#[fg=colour31]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=colour124,bold]'
    modified: '#[fg=colour39,bold]'
    untracked: '#[fg=colour219,bold]'
    stashed: '#[fg=purple,bold]'
    clean: '#[fg=green,bold]'
  layout: [' ',branch, ' ', remote, ' ', flags, ' ']
  options:
    branch_max_len: 0