set-option -g detach-on-destroy off
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256:color:RBG"

bind r source-file ~/.config/tmux/tmux.conf \; display '~/.tmux.conf sourced'


# Base Settings
set -g base-index 1

# Theme
set -g status-position top
set -g status-style 'bg=default,fg=white'
set -g pane-active-border-style 'fg=default,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g status-left-length 70
set -g status-left '#[fg=blue,bold]#S '
set -ga status-left '#(gitmux -cfg ./gitmux.conf"#{pane_current_path}")'
