set -g default-terminal "screen-256color"

# -- Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# -- General
set -g mouse 'on'
set -sg escape-time 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g allow-rename on
set -g @continuum-restore 'on'


# -- Keybinds
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration Reloaded!"
bind | split-window -h
bind - split-window -v
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# -- Status Bar

# -- Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'odedlaz/tmux-onedark-theme'

run '~/.config/tmux/plugins/tpm/tpm'
