set-option -g detach-on-destroy off
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256:color:RBG"

bind r source-file ~/.config/tmux/tmux.conf \; display '~/.tmux.conf sourced'


# Base Settings
set -g base-index 1


# -- Status Bar
set -g status on # set to `2` for double height
set -g status-interval 3
set -g status-justify left
set -g status-position top
set -g set-titles on # set terminal title
set -g allow-rename on
setw -g automatic-rename on # set to `on` in order to work with nvim auto titlestring updating
# set -g set-titles-string "#S | #W | #{pane_current_command}"
set -g set-titles-string "tmux [#{s/@//:window_id}][#P/#{window_panes}]{#F}:  #T"
set -g display-time 1000 # tmux messages are displayed for n milliseconds
set -g display-panes-time 800 # slightly longer pane indicators display time


set -g default-terminal "xterm-256color"
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

color_wait=magenta
color_copy=yellow
color_sync=red
color_tmux=color4
dark_text=color0
med_bg=#2122c
light_text=#ABB2BF
time_bg=color4
time_fg=color0
highlight=color4
status_bg=#191A21

set -g status on
set -g status-style fg=$light_text,bg=$status_bg
set -g destroy-unattached on
set -g pane-border-style bg=default,fg=black
set -g pane-active-border-style bg=default,fg=color8
set -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g escape-time 0
set -g focus-events on
set -g history-limit 3000
set -g history-file ~/.tmux_history
set -g monitor-activity off
set -g visual-activity off
set -g base-index 1
set -g pane-base-index 1
set -g -w automatic-rename off
set -g renumber-windows on
set -g bell-action none
set -g status-position top
set -g status-interval 5

set -g status-right-length 100
set -g status-left '#{tmux_mode_indicator}'

set -g status-right "#[fg=$light_text]#[bg=$med_bg,fg=$light_text] CPU: #[fg=$highlight]#{cpu_percentage}  #[fg=$light_text]RAM: #[fg=$highlight]#{ram_percentage} #[fg=$time_bg]#[bg=$time_bg,fg=$time_fg,bold] %A, %d %b %Y %I:%M %p "
set -g status-justify left

set -g window-status-current-format " #[fg=$highlight,bold][#I] #W"
set -g window-status-format " #[fg=$light_text][#I] #W"
